# Generated by Django 4.2.29 on 2026-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
