# Generated by Django 4.2.30 on 2026-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фіксована ставка, ₴/міс'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Відсоток від виручки, %'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фіксована ставка'), ('percent', 'Відсоток від виручки'), ('mixed', 'Ставка + відсоток')], default='percent', max_length=10, verbose_name='Тип нарахування'),
        ),
    ]
