# Generated by Django 4.2.30 on 2026-04-17 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
        ('accounts', '0005_salary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_hourly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка за годину (грн)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фіксована ставка'), ('percent', 'Відсоток від виручки'), ('mixed', 'Ставка + відсоток'), ('fixed_percent', 'Фікс + відсоток'), ('hourly', 'Погодинна')], default='percent', max_length=20, verbose_name='Тип нарахування'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Початок')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Кінець')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Годин')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='clinic.organization', verbose_name='Організація')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Зміна',
                'verbose_name_plural': 'Зміни',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['organization', 'date'], name='accounts_sh_organiz_cb1d40_idx'), models.Index(fields=['user', 'date'], name='accounts_sh_user_id_db2be0_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Початок періоду')),
                ('period_end', models.DateField(verbose_name='Кінець періоду')),
                ('shifts_count', models.PositiveIntegerField(default=0, verbose_name='Кількість змін')),
                ('hours_total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Всього годин')),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Виручка за період')),
                ('salary_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фіксована частина')),
                ('salary_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус (відсоток)')),
                ('salary_hourly_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='За години')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Утримання')),
                ('salary_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='До виплати')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Затверджено'), ('paid', 'Виплачено')], default='draft', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Затверджено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Виплачено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='clinic.organization', verbose_name='Організація')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Розрахунок зарплати',
                'verbose_name_plural': 'Розрахунки зарплат',
                'ordering': ['-period_end'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
