# Generated by Django 4.2.30 on 2026-04-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_per_shift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка за зміну, ₴'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_hourly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка за годину, ₴'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фіксована (грн/міс)'), ('percent', 'Відсоток від виручки'), ('fixed_percent', 'Фікс + відсоток'), ('per_shift', 'Ставка за зміну'), ('hourly', 'Погодинна')], default='percent', max_length=20, verbose_name='Тип нарахування'),
        ),
    ]
