# Generated by Django 4.2.29 on 2026-03-22 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('clients', '0002_visit_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('paid', 'Оплачено'), ('cancelled', 'Скасовано')], default='draft', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('discount_type', models.CharField(choices=[('percent', '%'), ('amount', '₴')], default='percent', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Клієнт')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'Рахунки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('service', 'Послуга'), ('product', 'Товар')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_type', models.CharField(choices=[('percent', '%'), ('amount', '₴')], default='percent', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_written_off', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'verbose_name': 'Рядок рахунку',
            },
        ),
    ]
