# Generated by Django 4.2.29 on 2026-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Готівка'), ('card', 'Картка')], max_length=10, null=True, verbose_name='Спосіб оплати'),
        ),
    ]
