# Generated by Django 4.2.29 on 2026-04-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_org_fk'),
        ('billing', '0003_invoice_fiscal_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinic.organization', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Готівка'), ('card', 'Картка')], max_length=10, null=True, verbose_name='Спосіб оплати'),
        ),
    ]
