# Generated by Django 4.2.29 on 2026-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_fiscal_page_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='invoice_org_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'payment_method'], name='invoice_org_payment_idx'),
        ),
    ]
