# Generated by Django 4.2.30 on 2026-04-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_invoice_org_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='billing.invoiceline'),
        ),
    ]
