# Generated by Django 4.2.30 on 2026-05-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text="Якщо увімкнено — послуга з'явиться на kizuna.com.ua/pricelist/", verbose_name='Показувати на сайті'),
        ),
    ]
