# Generated by Django 4.2.29 on 2026-03-26 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('icon', models.CharField(blank=True, help_text='Емоджі для відображення', max_length=10, verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Категорія витрат',
                'verbose_name_plural': 'Категорії витрат',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактна особа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('date', models.DateField(verbose_name='Дата')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('transfer', 'Переказ')], default='cash', max_length=10, verbose_name='Спосіб оплати')),
                ('description', models.CharField(max_length=500, verbose_name='Опис')),
                ('receipt_photo', models.ImageField(blank=True, upload_to='expenses/', verbose_name='Фото чеку / накладної')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Категорія')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто вніс')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Витрата',
                'verbose_name_plural': 'Витрати',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Внесення в касу'), ('withdrawal', 'Вилучення з каси'), ('card_to_cash', 'Картка → Готівка'), ('cash_to_card', 'Готівка → Картка')], max_length=15, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто вніс')),
            ],
            options={
                'verbose_name': 'Касова операція',
                'verbose_name_plural': 'Касові операції',
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
