# Generated by Django 4.2.29 on 2026-04-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_org_fk'),
        ('finance', '0002_financesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoperation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_operations', to='clinic.organization', verbose_name='Організація'),
        ),
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='clinic.organization', verbose_name='Організація'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='clinic.organization', verbose_name='Організація'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='clinic.organization', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
