# Generated by Django 4.2.29 on 2026-04-11 07:34

import apps.clinic.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financesettings_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, upload_to=apps.clinic.uploads.expense_receipt_path, verbose_name='Фото чеку / накладної'),
        ),
    ]
