# Generated by Django 4.2.30 on 2026-05-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('layout', models.JSONField(blank=True, default=list, help_text='[{type, x, y, w, h, config}]', verbose_name='Layout')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='clinic.organization', verbose_name='Організація')),
                ('owner', models.ForeignKey(blank=True, help_text='null = спільний дашборд організації', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборди',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(fields=('organization', 'owner', 'name'), name='uniq_dashboard_per_user'),
        ),
    ]
