# Generated by Django 4.2.29 on 2026-04-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_org_fk'),
        ('tg', '0004_telegrammessage_media_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_chats', to='clinic.organization', verbose_name='Організація'),
        ),
    ]
