# Generated by Django 4.2.29 on 2026-04-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_merge_clinic_settings'),
        ('tg', '0005_org_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='tg_user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='telegramchat',
            unique_together={('tg_user_id', 'organization')},
        ),
    ]
