# Generated by Django 4.2.29 on 2026-04-11 07:34

import apps.clinic.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_per_org_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='media_file',
            field=models.FileField(blank=True, upload_to=apps.clinic.uploads.tg_media_path),
        ),
    ]
