# Generated by Django 4.2.30 on 2026-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_telegramchat_receive_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='avatar_file_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
