# Generated by Django 4.2.30 on 2026-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_avatar_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Позначити як співробітника — отримуватиме системні сповіщення.', verbose_name='Співробітник'),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='receive_messages',
            field=models.BooleanField(default=False, help_text='Отримує сповіщення коли клієнт пише в бота.', verbose_name='Нові повідомлення'),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='receive_leads',
            field=models.BooleanField(default=False, help_text='Отримує повідомлення про нові заявки з сайту.', verbose_name='Заявки з сайту'),
        ),
    ]
