# Generated by Django 4.2.30 on 2026-04-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0012_add_staff_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReplyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('staff_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reply_prompts', to='tg.telegramchat')),
                ('target_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reply_inbound', to='tg.telegramchat')),
            ],
            options={
                'verbose_name': 'Запит швидкої відповіді',
                'verbose_name_plural': 'Запити швидкої відповіді',
                'indexes': [models.Index(fields=['staff_chat', 'prompt_message_id'], name='tg_quickrep_staff_c_0e8f52_idx')],
            },
        ),
    ]
