# Generated by Django 4.2.30 on 2026-05-18 11:43
# Manual: dedup existing (chat, tg_message_id) pairs before adding UniqueConstraint.

from django.db import migrations, models


def dedup_tg_messages(apps, schema_editor):
    """Видалити дублікати (chat, tg_message_id), залишивши найстаріший (min id)."""
    TelegramMessage = apps.get_model('tg', 'TelegramMessage')
    seen = {}
    to_delete = []
    qs = (
        TelegramMessage.objects
        .exclude(tg_message_id__isnull=True)
        .order_by('id')
        .values_list('id', 'chat_id', 'tg_message_id')
    )
    for pk, chat_id, tg_msg_id in qs:
        key = (chat_id, tg_msg_id)
        if key in seen:
            to_delete.append(pk)
        else:
            seen[key] = pk
    if to_delete:
        TelegramMessage.objects.filter(pk__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0014_perf_indexes'),
    ]

    operations = [
        migrations.RunPython(dedup_tg_messages, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='telegrammessage',
            constraint=models.UniqueConstraint(
                condition=models.Q(('tg_message_id__isnull', False)),
                fields=('chat', 'tg_message_id'),
                name='tgmsg_chat_tgmsgid_unique',
            ),
        ),
    ]
