# Generated by Django 4.2.30 on 2026-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0016_telegramchat_onboarding_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='autodialog_state',
            field=models.JSONField(blank=True, default=dict, help_text='Автодіалог з незареєстрованими: {"stage": "offered|declined|booking|done", "data": {...}}. Окремо від onboarding_state, бо той перезаписується цілком.', verbose_name='Стан автодіалогу'),
        ),
    ]
