# Generated by Django 4.2.29 on 2026-03-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вхідна ціна')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вихідна ціна')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Залишок')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, help_text='При меншому залишку — попередження', max_digits=10, verbose_name='Мін. залишок')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Назва')),
                ('short', models.CharField(max_length=10, verbose_name='Скорочення')),
            ],
            options={
                'verbose_name': 'Одиниця виміру',
                'verbose_name_plural': 'Одиниці виміру',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Прихід'), ('out', 'Списання'), ('adjust', 'Коригування')], max_length=10, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за од.')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рух складу',
                'verbose_name_plural': 'Рухи складу',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='Одиниця'),
        ),
    ]
