# Generated by Django 4.2.30 on 2026-04-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_receipt_photo'),
        ('inventory', '0005_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='finance.supplier', verbose_name='Постачальник'),
        ),
    ]
