# Generated by Django 4.2.30 on 2026-04-18 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_supplier_to_stock_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вхідна ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вихідна ціна'),
        ),
    ]
