# Generated by Django 4.2.30 on 2026-04-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
        ('inventory', '0007_alter_product_buy_price_alter_product_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Порожнє = глобальна (доступна всім)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='clinic.organization', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Назва'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_unit_per_org'),
        ),
    ]
