from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.ClientListView.as_view(), name='list'),
    path('patients/', views.PatientListView.as_view(), name='patient_list'),
    path('create/', views.ClientCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ClientDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.ClientUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.client_delete, name='delete'),
    path('<int:client_pk>/patients/create/', views.patient_create, name='patient_create'),
    path('patients/<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('patients/<int:pk>/edit/', views.patient_update, name='patient_edit'),
    path('patients/<int:pk>/delete/', views.patient_delete, name='patient_delete'),
    path('patients/<int:patient_pk>/visits/create/', views.visit_create, name='visit_create'),
    path('visits/<int:pk>/edit/', views.visit_update, name='visit_edit'),
    path('visits/<int:pk>/pdf/', views.visit_pdf, name='visit_pdf'),
    path('visits/<int:pk>/duplicate/', views.visit_duplicate, name='visit_duplicate'),
    path('patients/<int:patient_pk>/vaccines/create/', views.vaccine_create, name='vaccine_create'),
    path('vaccines/<int:pk>/edit/', views.vaccine_update, name='vaccine_edit'),
    path('patients/<int:pk>/set-doctor/', views.patient_set_doctor, name='patient_set_doctor'),
    path('patients/<int:patient_pk>/analyses/create/', views.analysis_create, name='analysis_create'),
    path('analyses/<int:pk>/delete/', views.analysis_delete, name='analysis_delete'),
    path('search/', views.client_search, name='search'),
    path('patients/<int:patient_pk>/weights/add/', views.weight_add, name='weight_add'),
    path('weights/<int:pk>/delete/', views.weight_delete, name='weight_delete'),
    path('patients/period/', views.patients_by_period, name='patients_period'),
    path('vaccines/overdue/', views.vaccines_overdue, name='vaccines_overdue'),
    path('hospitalization/', views.hospitalization_list, name='hospitalization_list'),
    path('patients/<int:patient_pk>/hospitalize/', views.hospitalization_create, name='hospitalization_create'),
    path('hospitalization/<int:pk>/discharge/', views.hospitalization_discharge, name='hospitalization_discharge'),
    # ── Нові views: медкартка, швидкий візит, фото, породи, вага, рецепти, документи, шаблони ──
    path('patients/<int:pk>/medical-card/', views.patient_medical_card, name='medical_card'),
    path('patients/<int:patient_pk>/quick-visit/', views.quick_visit, name='quick_visit'),
    path('patients/<int:pk>/photo-upload/', views.patient_photo_upload, name='patient_photo_upload'),
    path('breeds/', views.breed_suggestions, name='breed_suggestions'),
    path('diagnoses/', views.diagnosis_suggestions, name='diagnosis_suggestions'),
    path('patients/<int:patient_pk>/weight-alert/', views.weight_alert_check, name='weight_alert'),
    path('visits/<int:visit_pk>/prescriptions/create/', views.prescription_create, name='prescription_create'),
    path('prescriptions/<int:pk>/delete/', views.prescription_delete, name='prescription_delete'),
    path('patients/<int:patient_pk>/documents/upload/', views.document_upload, name='document_upload'),
    path('documents/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('visit-templates/', views.visit_template_manage, name='visit_templates'),
    path('visit-templates/json/', views.visit_templates_json, name='visit_templates_json'),
    path('audit/', views.audit_log_view, name='audit_log'),
    path('audit/<str:content_type>/<int:object_id>/', views.audit_log_object, name='audit_object'),
    path('health-diary/', views.health_diary, name='health_diary'),
    path('patients/<int:patient_pk>/ultrasound/create/', views.ultrasound_create, name='ultrasound_create'),
    path('ultrasound/<int:pk>/edit/', views.ultrasound_edit, name='ultrasound_edit'),
    path('ultrasound/<int:pk>/pdf/', views.ultrasound_pdf, name='ultrasound_pdf'),
    path('ultrasound/<int:pk>/delete/', views.ultrasound_delete, name='ultrasound_delete'),
]
