# Generated by Django 4.2.29 on 2026-03-22 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кіт'), ('rabbit', 'Кролик'), ('bird', 'Птах'), ('reptile', 'Рептилія'), ('other', 'Інше')], default='dog', max_length=20, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('sex', models.CharField(choices=[('male', 'Самець'), ('female', 'Самиця'), ('unknown', 'Невідомо')], default='unknown', max_length=10, verbose_name='Стать')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Масть/колір')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clients.client', verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
                'ordering': ('name',),
            },
        ),
    ]
