# Generated by Django 4.2.29 on 2026-03-22 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата прийому')),
                ('complaint', models.TextField(blank=True, verbose_name='Скарги')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Діагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Лікування')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Візит',
                'verbose_name_plural': 'Візити',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва вакцини')),
                ('date', models.DateField(verbose_name='Дата щеплення')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Наступне щеплення')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Серія')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccines', to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='clients.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцини',
                'ordering': ('-date',),
            },
        ),
    ]
