# Generated by Django 4.2.29 on 2026-03-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_visit_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=30, verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Кастрований/стерилізований'),
        ),
    ]
