# Generated by Django 4.2.29 on 2026-03-23 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_add_age_neutered_to_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='analyses/', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='clients.patient', verbose_name='Пацієнт')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
            ],
            options={
                'verbose_name': 'Аналіз',
                'verbose_name_plural': 'Аналізи',
                'ordering': ('-date',),
            },
        ),
    ]
