# Generated by Django 4.2.29 on 2026-03-24 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_add_patient_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата зважування')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вага (кг)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='clients.patient', verbose_name='Пацієнт')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто зважував')),
            ],
            options={
                'verbose_name': 'Вага',
                'verbose_name_plural': 'Записи ваги',
                'ordering': ('date',),
            },
        ),
    ]
