# Generated by Django 4.2.29 on 2026-04-11 07:34

import apps.clinic.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_org_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clinic.uploads.patient_photo_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='patientanalysis',
            name='image',
            field=models.ImageField(upload_to=apps.clinic.uploads.analysis_image_path, verbose_name='Фото'),
        ),
    ]
