# Generated by Django 4.2.30 on 2026-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_phone_alter_patient_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Нагадування відправлено'),
        ),
    ]
