# Generated by Django 4.2.30 on 2026-04-11 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0007_alter_organization_trial_expires_at'),
        ('clients', '0009_vaccine_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Персональна знижка клієнта (0–100)', max_digits=5, verbose_name='Знижка, %'),
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина госпіталізації')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Діагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Призначення')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('status', models.CharField(choices=[('active', 'На стаціонарі'), ('discharged', 'Виписаний')], default='active', max_length=20, verbose_name='Статус')),
                ('admitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата надходження')),
                ('discharged_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата виписки')),
                ('discharge_notes', models.TextField(blank=True, verbose_name='Нотатки при виписці')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='clinic.organization', verbose_name='Організація')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='clients.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Госпіталізація',
                'verbose_name_plural': 'Стаціонар',
                'ordering': ('-admitted_at',),
            },
        ),
    ]
