# Generated by Django 4.2.30 on 2026-04-17 04:52

import apps.clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0010_hospitalization_and_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Алергії на препарати, хронічні захворювання — видно на картці червоним', verbose_name='Алергії / хронічні'),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Дата повторного огляду', null=True, verbose_name='Контрольний візит'),
        ),
        migrations.CreateModel(
            name='VisitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва шаблону')),
                ('complaint', models.TextField(blank=True, verbose_name='Скарги')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Діагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Лікування')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_templates', to='clinic.organization')),
            ],
            options={
                'verbose_name': 'Шаблон візиту',
                'verbose_name_plural': 'Шаблони візитів',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200, verbose_name='Препарат')),
                ('dosage', models.CharField(max_length=200, verbose_name='Дозування')),
                ('frequency', models.CharField(help_text='Наприклад: 2 рази на день', max_length=100, verbose_name='Частота')),
                ('duration', models.CharField(help_text='Наприклад: 7 днів', max_length=100, verbose_name='Тривалість')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clients.patient', verbose_name='Пацієнт')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clients.visit', verbose_name='Візит')),
            ],
            options={
                'verbose_name': 'Призначення',
                'verbose_name_plural': 'Призначення',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('file', models.FileField(upload_to=apps.clients.models.patient_document_path, verbose_name='Файл')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.patient', verbose_name='Пацієнт')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ('-date',),
            },
        ),
    ]
