# Generated by Django 4.2.30 on 2026-04-17 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0011_add_patients_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name="Тип об'єкта")),
                ('object_id', models.PositiveIntegerField(verbose_name="ID об'єкта")),
                ('object_repr', models.CharField(max_length=255, verbose_name="Об'єкт")),
                ('action', models.CharField(choices=[('create', 'Створено'), ('update', 'Змінено'), ('delete', 'Видалено')], max_length=10, verbose_name='Дія')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Зміни')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Журнал аудиту',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='clients_aud_content_7acbb7_idx'), models.Index(fields=['organization', '-created_at'], name='clients_aud_organiz_940f8d_idx')],
            },
        ),
    ]
