# Generated by Django 4.2.30 on 2026-04-18 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_add_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Персональна знижка клієнта (0–100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка, %'),
        ),
    ]
