# Generated by Django 4.2.30 on 2026-04-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
        ('clients', '0013_alter_client_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('weekly', 'Щотижневе'), ('post_visit', 'Після візиту'), ('post_surgery', 'Після операції'), ('seasonal', 'Сезонне')], max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'Очікує відповіді'), ('ok', 'Все добре'), ('concern', 'Є питання'), ('no_response', 'Без відповіді')], default='pending', max_length=20, verbose_name='Статус')),
                ('question', models.TextField(verbose_name='Питання')),
                ('response_text', models.TextField(blank=True, verbose_name='Відповідь клієнта')),
                ('response_photo', models.ImageField(blank=True, null=True, upload_to='health_checks/', verbose_name='Фото відповіді')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Відправлено')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Відповідь отримана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='clinic.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='clients.patient', verbose_name='Пацієнт')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to='clients.visit', verbose_name="Пов'язаний візит")),
            ],
            options={
                'verbose_name': "Опитування здоров'я",
                'verbose_name_plural': "Опитування здоров'я",
                'ordering': ['-sent_at'],
            },
        ),
    ]
