# Generated by Django 4.2.30 on 2026-04-19 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0014_add_health_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltrasoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата дослідження')),
                ('liver_size', models.CharField(blank=True, help_text='Норма / збільшена / зменшена', max_length=50, verbose_name='Розмір печінки')),
                ('liver_echogenicity', models.CharField(blank=True, help_text='Нормальна / підвищена / знижена / неоднорідна', max_length=50, verbose_name='Ехогенність печінки')),
                ('liver_structure', models.CharField(blank=True, help_text='Однорідна / неоднорідна, дифузні зміни', max_length=100, verbose_name='Структура печінки')),
                ('liver_vessels', models.CharField(blank=True, help_text='Не розширені / розширені', max_length=100, verbose_name='Судини печінки')),
                ('liver_notes', models.TextField(blank=True, verbose_name='Коментар (печінка)')),
                ('gallbladder_size', models.CharField(blank=True, help_text='Довжина × ширина мм', max_length=50, verbose_name='Розмір ЖМ')),
                ('gallbladder_wall', models.CharField(blank=True, help_text='Не потовщена / потовщена до ___ мм', max_length=50, verbose_name='Стінка ЖМ')),
                ('gallbladder_content', models.CharField(blank=True, help_text='Анехогенний / сладж / конкременти', max_length=100, verbose_name='Вміст ЖМ')),
                ('gallbladder_notes', models.TextField(blank=True, verbose_name='Коментар (ЖМ)')),
                ('spleen_size', models.CharField(blank=True, help_text='Норма / збільшена', max_length=50, verbose_name='Розмір селезінки')),
                ('spleen_echogenicity', models.CharField(blank=True, max_length=50, verbose_name='Ехогенність селезінки')),
                ('spleen_structure', models.CharField(blank=True, max_length=100, verbose_name='Структура селезінки')),
                ('spleen_notes', models.TextField(blank=True, verbose_name='Коментар (селезінка)')),
                ('kidney_left_size', models.CharField(blank=True, help_text='Довжина × ширина мм', max_length=50, verbose_name='Ліва нирка розмір')),
                ('kidney_left_cortex', models.CharField(blank=True, help_text='мм', max_length=50, verbose_name='Кірковий шар лівої')),
                ('kidney_right_size', models.CharField(blank=True, help_text='Довжина × ширина мм', max_length=50, verbose_name='Права нирка розмір')),
                ('kidney_right_cortex', models.CharField(blank=True, help_text='мм', max_length=50, verbose_name='Кірковий шар правої')),
                ('kidney_echogenicity', models.CharField(blank=True, max_length=50, verbose_name='Ехогенність нирок')),
                ('kidney_pelvis', models.CharField(blank=True, help_text='Не розширена / розширена до ___ мм', max_length=100, verbose_name='Ниркова миска')),
                ('kidney_notes', models.TextField(blank=True, verbose_name='Коментар (нирки)')),
                ('bladder_filling', models.CharField(blank=True, help_text='Помірне / достатнє / переповнений', max_length=50, verbose_name='Наповнення СМ')),
                ('bladder_wall', models.CharField(blank=True, help_text='Не потовщена / потовщена до ___ мм', max_length=50, verbose_name='Стінка СМ')),
                ('bladder_content', models.CharField(blank=True, help_text='Анехогенний / осад / конкременти', max_length=100, verbose_name='Вміст СМ')),
                ('bladder_notes', models.TextField(blank=True, verbose_name='Коментар (СМ)')),
                ('gi_notes', models.TextField(blank=True, help_text='Стінка, перистальтика, вміст, лімфовузли', verbose_name='ШКТ')),
                ('reproductive_notes', models.TextField(blank=True, help_text='Матка / простата / яєчники', verbose_name='Репродуктивна система')),
                ('free_fluid', models.CharField(blank=True, help_text="Відсутня / присутня (локалізація, об'єм)", max_length=100, verbose_name='Вільна рідина')),
                ('conclusion', models.TextField(blank=True, verbose_name='Висновок')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендації')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasounds', to='clients.patient', verbose_name='Пацієнт')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultrasounds', to='clients.visit')),
            ],
            options={
                'verbose_name': 'Протокол УЗД',
                'verbose_name_plural': 'Протоколи УЗД',
                'ordering': ['-date'],
            },
        ),
    ]
