# Generated by Django 4.2.30 on 2026-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_add_ultrasound_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='species',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кіт'), ('rabbit', 'Кролик'), ('bird', 'Птах'), ('hamster', "Хом'як"), ('guinea_pig', 'Морська свинка'), ('ferret', 'Тхір'), ('chinchilla', 'Шиншила'), ('rat', 'Щур / Миша'), ('turtle', 'Черепаха'), ('reptile', 'Ящірка / Змія'), ('fish', 'Риба'), ('hedgehog', 'Їжак'), ('other', 'Інше')], default='dog', max_length=20, verbose_name='Вид'),
        ),
    ]
