# Generated by Django 4.2.30 on 2026-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архівування'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Архівовано'),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архівування'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Архівовано'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'is_archived', 'last_name'], name='client_org_arch_lname_idx'),
        ),
    ]
