# Generated by Django 4.2.30 on 2026-08-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_patientanalysis_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.visit', verbose_name='Візит'),
        ),
    ]
