# Generated by Django 4.2.30 on 2026-08-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_duration'),
        ('clients', '0020_patientdocument_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='З якого запису календаря проведено цей прийом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment', verbose_name='Запис у календарі'),
        ),
    ]
