# Generated by Django 4.2.30 on 2026-05-19 10:40

import apps.carddav.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDAVToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.carddav.models._generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('sync_token', models.PositiveBigIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carddav_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CardDAV токен',
                'verbose_name_plural': 'CardDAV токени',
            },
        ),
    ]
