# Generated by Django 4.2.29 on 2026-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_org_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicSettings',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bot_base_url',
            field=models.CharField(blank=True, default='', help_text='Наприклад: https://crm.kizuna.com.ua', max_length=200, verbose_name='Base URL для PDF-генерації'),
        ),
        migrations.AddField(
            model_name='organization',
            name='checkbox_license_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Checkbox License Key'),
        ),
        migrations.AddField(
            model_name='organization',
            name='checkbox_pin',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Checkbox PIN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency_symbol',
            field=models.CharField(default='₴', max_length=5, verbose_name='Символ валюти'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Коротка назва'),
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Отримати у @BotFather. Наприклад: 123456:ABC-DEF...', max_length=200, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Веб-сайт / домен'),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_hours',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Години роботи'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Латинські літери/цифри. Використовується для субдомену.', unique=True, verbose_name='Ідентифікатор'),
        ),
    ]
