# Generated by Django 4.2.29 on 2026-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_merge_clinic_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Автоматично генерується при реєстрації webhook. Не змінювати вручну.', max_length=256, verbose_name='Telegram Webhook Secret'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bot_base_url',
            field=models.CharField(blank=True, default='', help_text='Наприклад: https://crm.kizuna.com.ua', max_length=200, verbose_name='Адреса сайту (для PDF через Telegram)'),
        ),
    ]
