# Generated by Django 4.2.29 on 2026-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_organization_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, help_text='Якщо вказано — акаунт заблокується після цієї дати.', null=True, verbose_name='Доступ до'),
        ),
    ]
