# Generated by Django 4.2.30 on 2026-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_default_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='role_menu_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доступ до меню по ролях'),
        ),
    ]
