# Generated by Django 4.2.30 on 2026-04-16 09:38

import apps.clinic.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_add_role_menu_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notify_appointment_24h',
            field=models.BooleanField(default=True, verbose_name='Нагадування за 24 год'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_appointment_2h',
            field=models.BooleanField(default=True, verbose_name='Нагадування за 2 год'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_vaccines',
            field=models.BooleanField(default=True, verbose_name='Нагадування про вакцини'),
        ),
        migrations.AddField(
            model_name='organization',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, verbose_name='Тривалість слоту (хв)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_days',
            field=models.JSONField(default=apps.clinic.models._default_work_days, help_text='Список робочих днів: 0=Пн, 1=Вт, 2=Ср, 3=Чт, 4=Пт, 5=Сб, 6=Нд', verbose_name='Робочі дні'),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Кінець роботи'),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_start',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Початок роботи'),
        ),
    ]
