# Generated by Django 4.2.30 on 2026-05-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_add_schedule_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=200, unique=True, verbose_name='Order reference')),
                ('plan_key', models.CharField(blank=True, max_length=50, verbose_name='Тариф')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сирий payload')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Оброблено')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='clinic.organization')),
            ],
            options={
                'verbose_name': 'Платіжна транзакція',
                'verbose_name_plural': 'Платіжні транзакції',
                'indexes': [models.Index(fields=['organization', '-processed_at'], name='clinic_paym_organiz_ed15c7_idx')],
            },
        ),
    ]
