# Generated by Django 4.2.30 on 2026-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(blank=True, choices=[('base', 'База — ₴900/міс'), ('support', 'Підтримка — ₴2 200/міс'), ('custom', 'Індивідуальний — від ₴4 500/міс')], default='', max_length=20, verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='DemoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('utm_source', models.CharField(blank=True, default='', max_length=120)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=120)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=120)),
                ('referer', models.CharField(blank=True, default='', max_length=500)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('notified', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='clinic_demo_created_d7c0a7_idx')],
            },
        ),
    ]
