# Generated by Django 4.2.30 on 2026-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_demotenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('utm_source', models.CharField(blank=True, default='', max_length=120)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=120)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=120)),
                ('referer', models.CharField(blank=True, default='', max_length=500)),
                ('notified', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='clinic_cont_created_185338_idx')],
            },
        ),
    ]
