# Generated by Django 4.2.29 on 2026-03-22 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_visit_vaccine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Початок')),
                ('duration', models.IntegerField(choices=[(15, '15 хв'), (30, '30 хв'), (45, '45 хв'), (60, '1 год'), (90, '1.5 год'), (120, '2 год')], default=30, verbose_name='Тривалість (хв)')),
                ('status', models.CharField(choices=[('scheduled', 'Заплановано'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано'), ('no_show', 'Не прийшов')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client', verbose_name='Клієнт')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Лікар')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.patient', verbose_name='Пацієнт')),
                ('services', models.ManyToManyField(blank=True, related_name='appointments', to='services.service', verbose_name='Заплановані послуги')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['starts_at'],
            },
        ),
    ]
