# Generated by Django 4.2.29 on 2026-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_org_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'starts_at'], name='appt_org_starts_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'status'], name='appt_org_status_idx'),
        ),
    ]
