# Generated by Django 4.2.30 on 2026-04-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_add_role_menu_config'),
        ('appointments', '0003_appointment_appt_org_starts_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('pet_name', models.CharField(blank=True, max_length=100, verbose_name='Кличка')),
                ('pet_type', models.CharField(blank=True, max_length=50, verbose_name='Вид тварини')),
                ('service_note', models.CharField(blank=True, max_length=255, verbose_name='Причина звернення')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Бажана дата')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Бажаний час')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processed', 'Оброблена'), ('cancelled', 'Скасована')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(default='website', max_length=100, verbose_name='Джерело')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clinic.organization', verbose_name='Організація')),
            ],
            options={
                'verbose_name': 'Заявка з сайту',
                'verbose_name_plural': 'Заявки з сайту',
                'ordering': ['-created_at'],
            },
        ),
    ]
