# Generated by Django 4.2.30 on 2026-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_reminder_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 хв'), (30, '30 хв'), (45, '45 хв'), (60, '1 год'), (90, '1.5 год'), (120, '2 год'), (150, '2.5 год'), (180, '3 год'), (240, '4 год'), (300, '5 год')], default=30, verbose_name='Тривалість (хв)'),
        ),
    ]
